# Generated by Django 4.2.7 on 2023-12-12 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_course_price_remove_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='vietnam_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 9, 48, 26, 542527, tzinfo=datetime.timezone.utc)),
        ),
    ]
