# Generated by Django 4.2.7 on 2023-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_course_created_at_course_vietnam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vietnam_time',
            field=models.DateTimeField(),
        ),
    ]
